In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
arr1 = np.arange(9).reshape((3,3))

In [3]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [5]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
ser1 =  Series([0,1,2],index=['T','U','V'])

In [7]:
ser1

T    0
U    1
V    2
dtype: int64

In [8]:
ser2 = Series([3,4],index=['X','Y'])

In [9]:
ser2

X    3
Y    4
dtype: int64

In [10]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [11]:
pd.concat([ser1,ser2],axis=1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [12]:
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [13]:
dframe1 = DataFrame(np.random.randn(4,3), columns=['X', 'Y', 'Z'])

In [14]:
dframe2 = DataFrame(np.random.randn(3, 3), columns=['Y', 'Q', 'X'])

In [15]:
dframe1

X         Y         Z
0  0.950720 -1.197288  0.336223
1  1.596116  0.695955  0.074686
2 -0.578227  0.896804  0.227282
3 -0.629824 -0.457951  0.885248

In [17]:
dframe2

Y         Q         X
0 -0.069562  1.670167  0.095961
1 -0.602269 -0.691389 -1.248801
2  0.529430 -1.564964 -0.906695

In [18]:
pd.concat([dframe1,dframe2])

X         Y         Z         Q
0  0.950720 -1.197288  0.336223       NaN
1  1.596116  0.695955  0.074686       NaN
2 -0.578227  0.896804  0.227282       NaN
3 -0.629824 -0.457951  0.885248       NaN
0  0.095961 -0.069562       NaN  1.670167
1 -1.248801 -0.602269       NaN -0.691389
2 -0.906695  0.529430       NaN -1.564964

In [19]:
pd.concat([dframe1,dframe2],ignore_index=True)

X         Y         Z         Q
0  0.950720 -1.197288  0.336223       NaN
1  1.596116  0.695955  0.074686       NaN
2 -0.578227  0.896804  0.227282       NaN
3 -0.629824 -0.457951  0.885248       NaN
4  0.095961 -0.069562       NaN  1.670167
5 -1.248801 -0.602269       NaN -0.691389
6 -0.906695  0.529430       NaN -1.564964