In [1]:
import numpy as np


In [2]:
arr = np.arange(5)

In [3]:
arr

array([0, 1, 2, 3, 4])

In [4]:
np.save('myarray',arr)

In [5]:
arr = np.arange(10)

In [6]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.load('myarray.npy')

array([0, 1, 2, 3, 4])